# Generated by Django 5.0.4 on 2024-04-28 16:43

import files.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('upload_dateinfos', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(default=None, upload_to=files.models.generate_unique_filename)),
                ('idToInteger', models.CharField(default=0, max_length=64, unique=True)),
            ],
            options={
                'ordering': ['-upload_dateinfos'],
            },
        ),
    ]
